# Generated by Django 5.1.4 on 2025-03-10 10:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_ticket_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tickets', to='app.tickettag'),
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ccs',
        ),
        migrations.DeleteModel(
            name='TicketTagAssignment',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ccs',
            field=models.ManyToManyField(blank=True, related_name='tickets_ccd', to=settings.AUTH_USER_MODEL),
        ),
    ]
