# Generated by Django 6.0.4 on 2026-05-14 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_ticket_due_at_comment_via_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zendesk_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zendesk_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('domain_names', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='satisfactionrating',
            name='assignee_zendesk_id',
        ),
        migrations.RemoveField(
            model_name='satisfactionrating',
            name='requester_zendesk_id',
        ),
        migrations.RemoveField(
            model_name='satisfactionrating',
            name='zendesk_ticket_id',
        ),
        migrations.AddField(
            model_name='group',
            name='zendesk_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='satisfactionrating',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='satisfaction_ratings_assignee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='satisfactionrating',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='satisfaction_ratings_requester', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='zendesk_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.RunSQL("UPDATE app_ticket SET brand = NULL"),
        migrations.AlterField(
            model_name='ticket',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='app.brand'),
        ),
        migrations.RunSQL("UPDATE app_user SET organization = NULL"),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='app.organization'),
        ),
        migrations.DeleteModel(
            name='TicketHistory',
        ),
    ]
