# Generated by Django 6.0.4 on 2026-06-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_operational_backend_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='first_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
