# Generated by Django 6.0.4 on 2026-06-10 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_seed_default_assignment_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='slapolicy',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sla_policies', to='app.brand'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='first_response_met',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='problem',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'problem'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='app.ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_risk_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='channel',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('web', 'Web'), ('phone', 'Teléfono'), ('api', 'API'), ('chat', 'Chat'), ('twitter', 'Twitter'), ('twitter_dm', 'Twitter DM'), ('twitter_like', 'Twitter Like'), ('internal', 'Interno')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(blank=True, choices=[('question', 'Consulta'), ('incident', 'Incidencia'), ('problem', 'Problema'), ('task', 'Tarea')], max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['is_deleted', 'merged_into', 'brand', 'status'], name='app_ticket_live_brand_idx'),
        ),
    ]
