# Generated by Django 6.0.4 on 2026-06-10 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_normalize_type_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_key', models.CharField(blank=True, default='', max_length=64)),
                ('provider', models.CharField(blank=True, choices=[('m365', 'Microsoft 365'), ('ses', 'Amazon SES')], default='', max_length=10)),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('suppressed', 'Suppressed')], db_index=True, default='queued', max_length=16)),
                ('result', models.CharField(blank=True, max_length=64, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('dedup_key', models.CharField(blank=True, max_length=190, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_email_logs', to='app.brand')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_email_logs', to='app.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResponseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64)),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', max_length=5)),
                ('subject', models.CharField(max_length=255)),
                ('body_html', models.TextField()),
                ('body_text', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response_templates', to='app.brand')),
            ],
            options={
                'ordering': ['key', 'language'],
                'unique_together': {('key', 'brand', 'language')},
            },
        ),
    ]
