# Generated by Django 6.0.4 on 2026-06-10 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_seed_ticket_created_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, default='classification', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('suggested_type', models.CharField(blank=True, max_length=32, null=True)),
                ('suggested_category', models.CharField(blank=True, max_length=255, null=True)),
                ('suggested_priority', models.CharField(blank=True, max_length=32, null=True)),
                ('suggested_language', models.CharField(blank=True, max_length=10, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('field_confidences', models.JSONField(blank=True, default=dict)),
                ('reasoning', models.TextField(blank=True, null=True)),
                ('applied_fields', models.JSONField(blank=True, default=list)),
                ('input_fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('input_excerpt', models.TextField(blank=True, default='')),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('prompt_version', models.CharField(blank=True, default='v1', max_length=20)),
                ('input_tokens', models.IntegerField(blank=True, null=True)),
                ('output_tokens', models.IntegerField(blank=True, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='app.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ticket', 'kind', 'status'], name='app_aianalysis_tks_idx')],
            },
        ),
    ]
