# Generated by Django 6.0.4 on 2026-06-11 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_ticket_ai_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField(default=list)),
                ('content_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('dim', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='app.ticket')),
            ],
        ),
    ]
