# Generated by Django 6.0.4 on 2026-06-11 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_ticketembedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='slapolicy',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sla_policies', to='app.organization'),
        ),
    ]
