# Generated by Django 6.0.4 on 2026-07-28 11:28
#
# Habilita valoraciones de satisfacción propias (no importadas de Zendesk).
#
# Ticket.resolved_at queda a NULL en todo lo existente A PROPÓSITO: es el reloj del
# que cuelga el barrido de encuestas, así que no backfillearlo es lo que evita
# encuestar de golpe años de tickets ya resueltos el día que se active el envío.

import django.db.models.deletion
from django.db import migrations, models


def mark_existing_as_zendesk(apps, schema_editor):
    """Lo que ya había en la tabla vino del importador; el default es 'native'."""
    SatisfactionRating = apps.get_model('app', 'SatisfactionRating')
    SatisfactionRating.objects.filter(zendesk_id__isnull=False).update(source='zendesk')


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_slapolicy_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='satisfactionrating',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='satisfactionrating',
            name='offered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='satisfactionrating',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='satisfactionrating',
            name='source',
            field=models.CharField(choices=[('zendesk', 'Zendesk'), ('native', 'TicketFlow')], db_index=True, default='native', max_length=16),
        ),
        migrations.AddField(
            model_name='satisfactionrating',
            name='token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='satisfactionrating',
            name='zendesk_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='SatisfactionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64)),
                ('label', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', max_length=5)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['position', 'label'],
                'unique_together': {('code', 'language')},
            },
        ),
        migrations.AddField(
            model_name='satisfactionrating',
            name='reason_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to='app.satisfactionreason'),
        ),
        migrations.RunPython(mark_existing_as_zendesk, migrations.RunPython.noop),
    ]
