# Generated by Django 6.0.4 on 2026-08-26 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_assignment_rule_scope_multiple'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='original_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='attachment',
            name='size',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attachment',
            name='storage_backend',
            field=models.CharField(choices=[('local', 'Local'), ('s3', 'Amazon S3')], default='local', max_length=16),
        ),
        migrations.AddField(
            model_name='attachment',
            name='storage_key',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.CreateModel(
            name='HelpCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('service', models.CharField(db_index=True, max_length=100)),
                ('domains', models.JSONField(blank=True, default=list)),
                ('default_locale', models.CharField(default='es', max_length=10)),
                ('supported_locales', models.JSONField(blank=True, default=list)),
                ('tagline_es', models.CharField(blank=True, default='', max_length=255)),
                ('tagline_en', models.CharField(blank=True, default='', max_length=255)),
                ('primary_color', models.CharField(default='#172033', max_length=20)),
                ('accent_color', models.CharField(default='#7c3aed', max_length=20)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_centers', to='app.brand')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HelpCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(db_index=True, max_length=10)),
                ('source_id', models.BigIntegerField(blank=True, null=True)),
                ('translation_key', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('slug', models.SlugField(max_length=180)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('position', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(db_index=True, default=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='app.helpcenter')),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HelpSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.BigIntegerField(blank=True, null=True)),
                ('translation_key', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('slug', models.SlugField(max_length=180)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('position', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(db_index=True, default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='app.helpcategory')),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('translation_key', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('slug', models.SlugField(max_length=220)),
                ('title', models.CharField(max_length=500)),
                ('body_html', models.TextField(blank=True, default='')),
                ('body_text', models.TextField(blank=True, default='')),
                ('promoted', models.BooleanField(db_index=True, default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('source_url', models.URLField(blank=True, default='', max_length=1000)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='app.helpsection')),
            ],
            options={
                'ordering': ['position', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PublicTicketAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(db_index=True, max_length=64)),
                ('email_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_attempts', to='app.helpcenter')),
            ],
        ),
        migrations.AddIndex(
            model_name='helpcategory',
            index=models.Index(fields=['center', 'locale', 'published'], name='help_category_list_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='helpcategory',
            unique_together={('center', 'locale', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='helpsection',
            unique_together={('category', 'slug')},
        ),
        migrations.AddIndex(
            model_name='helparticle',
            index=models.Index(fields=['source_id', 'published'], name='help_article_source_idx'),
        ),
        migrations.AddIndex(
            model_name='helparticle',
            index=models.Index(fields=['promoted', 'published'], name='help_article_promoted_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='helparticle',
            unique_together={('section', 'slug')},
        ),
        migrations.AddIndex(
            model_name='publicticketattempt',
            index=models.Index(fields=['center', 'ip_hash', 'created_at'], name='public_ticket_ip_idx'),
        ),
        migrations.AddIndex(
            model_name='publicticketattempt',
            index=models.Index(fields=['center', 'email_hash', 'created_at'], name='public_ticket_email_idx'),
        ),
    ]
