# Generated by Django 5.1.4 on 2025-01-16 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='comment_id',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='attachment',
            old_name='ticket_id',
            new_name='ticket',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='ticket_id',
            new_name='ticket',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='assignee_id',
            new_name='assignee',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='requester_id',
            new_name='requester',
        ),
        migrations.RenameField(
            model_name='tickethistory',
            old_name='ticket_id',
            new_name='ticket',
        ),
        migrations.RenameField(
            model_name='tickettagassignment',
            old_name='tag_id',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='tickettagassignment',
            old_name='ticket_id',
            new_name='ticket',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='role_id',
            new_name='role',
        ),
    ]
