# Generated by Django 5.1.4 on 2025-09-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_ticket_tags_remove_ticket_ccs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
