# Generated by Django 5.1.4 on 2025-09-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_comment_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si la cuenta está activa. Desmárcalo para deshabilitarla.'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Permite acceder al admin de Django.'),
        ),
    ]
